"""Arrow and JSONL cache helpers."""

from __future__ import annotations

import json
import re
import time
from pathlib import Path
from typing import Any, Iterable

import pyarrow as pa
import pyarrow.ipc as pa_ipc


def write_arrow_table(path: Path, table: pa.Table) -> None:
    """Write a single Arrow IPC file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with pa.OSFile(str(path), "wb") as sink:
        with pa_ipc.new_file(sink, table.schema) as writer:
            writer.write_table(table)


def read_arrow_table(path: Path) -> pa.Table:
    """Read a single Arrow IPC file."""
    with pa.memory_map(str(path), "r") as source:
        reader = pa_ipc.RecordBatchFileReader(source)
        return reader.read_all()


class JsonlShardWriter:
    """Buffer JSONL records into cache shards and merge them later."""

    def __init__(
        self,
        cache_dir: Path,
        stem: str,
        *,
        flush_rows: int,
    ) -> None:
        self.cache_dir = cache_dir
        self.stem = stem
        self.flush_rows = max(flush_rows, 1)
        self._buffer: list[str] = []
        self._rows = 0
        self._shard_idx = 0
        self._shards: list[Path] = []
        self._flushes = 0
        self._flush_seconds = 0.0
        self._write_flushes = 0
        self._write_flush_seconds = 0.0
        self._finalize_flushes = 0
        self._finalize_flush_seconds = 0.0
        self._finalize_merge_seconds = 0.0
        self._merged_lines = 0

    def write(self, record: dict[str, Any]) -> None:
        self._buffer.append(json.dumps(record, ensure_ascii=False))
        self._rows += 1
        if len(self._buffer) >= self.flush_rows:
            self.flush(reason="write")

    def flush(self, *, reason: str = "write") -> None:
        if not self._buffer:
            return
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        shard_path = self.cache_dir / f"{self.stem}-{self._shard_idx:05d}.jsonl"
        t0 = time.perf_counter()
        shard_path.write_text("\n".join(self._buffer) + "\n", encoding="utf-8")
        elapsed = time.perf_counter() - t0
        self._flush_seconds += elapsed
        if reason == "finalize":
            self._finalize_flushes += 1
            self._finalize_flush_seconds += elapsed
        else:
            self._write_flushes += 1
            self._write_flush_seconds += elapsed
        self._shards.append(shard_path)
        self._shard_idx += 1
        self._flushes += 1
        self._buffer.clear()

    def finalize(self, output_path: Path) -> int:
        self.flush(reason="finalize")
        output_path.parent.mkdir(parents=True, exist_ok=True)
        t0 = time.perf_counter()
        with output_path.open("w", encoding="utf-8") as out:
            for shard in self._shards:
                with shard.open("r", encoding="utf-8") as handle:
                    for line in handle:
                        out.write(line)
                        self._merged_lines += 1
        self._finalize_merge_seconds += time.perf_counter() - t0
        return self._rows

    def snapshot(self) -> dict[str, Any]:
        """Return accumulated write-timing metadata."""
        return {
            "rows": self._rows,
            "flushes": self._flushes,
            "flush_seconds": self._flush_seconds,
            "write_flushes": self._write_flushes,
            "write_flush_seconds": self._write_flush_seconds,
            "finalize_flushes": self._finalize_flushes,
            "finalize_flush_seconds": self._finalize_flush_seconds,
            "finalize_merge_seconds": self._finalize_merge_seconds,
            "merged_lines": self._merged_lines,
        }


def cleanup_generated_cache_artifacts(
    cache_dir: Path,
    *,
    cache_paths: Iterable[Path],
    jsonl_shard_stems: Iterable[str],
) -> dict[str, int]:
    """Remove cache artifacts generated by this pipeline run."""
    candidates: set[Path] = set()
    for path in cache_paths:
        if path.exists() and path.is_file():
            candidates.add(path)

    if cache_dir.exists():
        for stem in jsonl_shard_stems:
            shard_re = re.compile(rf"{re.escape(stem)}-\d{{5}}\.jsonl")
            for path in cache_dir.glob(f"{stem}-*.jsonl"):
                if path.is_file() and shard_re.fullmatch(path.name):
                    candidates.add(path)

    deleted_files = 0
    deleted_bytes = 0
    for path in sorted(candidates):
        try:
            stat = path.stat()
            path.unlink()
        except FileNotFoundError:
            continue
        deleted_files += 1
        deleted_bytes += int(stat.st_size)

    return {
        "deleted_files": deleted_files,
        "deleted_bytes": deleted_bytes,
    }
